### PR TITLE
Added Link component to Navbar.js and routed Product Page 

### PR DESCRIPTION
**Pull request by jerome0caruso**
# Description
Routed the Product page using the link component

Fixes # (issues)
No more full page refreshes when changing pages.

## Changes made:
-import link component from react-router 
-routed the Products page
- 

 # Type of change:
  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [ *] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist:
  - [ *] I have read the contributing documentation.
  - [ *] My code follows the code style of this project.
  - [ *] My code has been linted.
  - [ *] I have performed a self-review of my code.
  - [ ] I have commented my code, particularly the hard to understand areas.
  - [ ] I have added tests to cover my changes (if applicable).
  - [ *] My changes generate no new warnings.
  - [ *] There are no merge conflicts.

### CODE REVIEW

**Comment by jerome0caruso** [comment]
Yes, you were correct, thank you!  I removed them and pushed a new file!

**Comment by robpedersendev** [comment]
Without those Curly's, does it appear to load correctly? 

When you click on the link, does it take you to the location?

**Comment by jerome0caruso** [comment]
Yep

**Comment by robpedersendev** [comment]
> e

PERFECT!

**Pull request merged**
